name: Pylint 
on: push

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install pylint
          sudo apt-get install git
          git clone https://github.com/peterhinch/micropython-nano-gui
      - name: Analyze code with Pylint
        run:
          pylint src/*.py
          
